from __future__ import annotations

from invoice_audit_env.models import Invoice, PolicyRules, PurchaseOrder, TaskFixture, VendorProfile


TASK_FIXTURES: dict[str, TaskFixture] = {
    "easy_single_mismatch": TaskFixture(
        task_id="easy_single_mismatch",
        difficulty="easy",
        description="Single amount mismatch and one clean invoice.",
        invoices=[
            Invoice(
                invoice_id="INV-E-001",
                vendor_name="Northwind Supplies",
                amount=1250.00,
                tax_code="GST5",
                due_date="2026-04-20",
                po_number="PO-1001",
                currency="USD",
                line_items=["office chairs"],
                received_at="2026-04-02",
            ),
            Invoice(
                invoice_id="INV-E-002",
                vendor_name="Northwind Supplies",
                amount=500.00,
                tax_code="GST5",
                due_date="2026-04-18",
                po_number="PO-1002",
                currency="USD",
                line_items=["desks"],
                received_at="2026-04-02",
            ),
        ],
        purchase_orders=[
            PurchaseOrder(po_number="PO-1001", vendor_name="Northwind Supplies", approved_amount=1000.00, allowed_tax_codes=["GST5"], approval_threshold=2000.0),
            PurchaseOrder(po_number="PO-1002", vendor_name="Northwind Supplies", approved_amount=500.00, allowed_tax_codes=["GST5"], approval_threshold=2000.0),
        ],
        vendors=[VendorProfile(vendor_name="Northwind Supplies", risk_level="low", known_aliases=[], historical_flags=[])],
        policies=PolicyRules(max_due_days=30, duplicate_window_days=7, split_threshold_amount=1000),
        expected_outcome="request_correction",
        perfect_actions=["review_invoice", "request_correction"],
        worst_actions=["approve_invoice"],
        max_steps=6,
        clean_invoice_ids=["INV-E-002"],
        escalation_required_invoice_ids=[],
        contradiction_pairs=[["approve_invoice", "request_correction"]],
        success_keywords=["mismatch", "po amount"],
        unsafe_approval_keywords=["mismatch"],
        expected_checks=["amount", "tax_code"],
    ),
    "medium_policy_tangle": TaskFixture(
        task_id="medium_policy_tangle",
        difficulty="medium",
        description="Policy violations across tax and due-date with one clean invoice.",
        invoices=[
            Invoice(
                invoice_id="INV-M-001",
                vendor_name="Blue River Logistics",
                amount=4800.00,
                tax_code="VAT18",
                due_date="2026-06-30",
                po_number="PO-2001",
                currency="USD",
                line_items=["freight"],
                received_at="2026-04-02",
            ),
            Invoice(
                invoice_id="INV-M-002",
                vendor_name="Blue River Logistics",
                amount=1800.00,
                tax_code="VAT5",
                due_date="2026-04-20",
                po_number="PO-2002",
                currency="USD",
                line_items=["warehouse fee"],
                received_at="2026-04-02",
            ),
        ],
        purchase_orders=[
            PurchaseOrder(po_number="PO-2001", vendor_name="Blue River Logistics", approved_amount=4800.00, allowed_tax_codes=["VAT5"], approval_threshold=3000.0),
            PurchaseOrder(po_number="PO-2002", vendor_name="Blue River Logistics", approved_amount=1800.00, allowed_tax_codes=["VAT5"], approval_threshold=3000.0),
        ],
        vendors=[VendorProfile(vendor_name="Blue River Logistics", risk_level="medium", known_aliases=["BlueRiver"], historical_flags=["late_docs"])],
        policies=PolicyRules(max_due_days=30, duplicate_window_days=10, split_threshold_amount=4000),
        expected_outcome="escalate_case",
        perfect_actions=["review_invoice", "request_correction", "escalate_case"],
        worst_actions=["approve_invoice"],
        max_steps=8,
        clean_invoice_ids=["INV-M-002"],
        escalation_required_invoice_ids=["INV-M-001"],
        contradiction_pairs=[["approve_invoice", "escalate_case"]],
        success_keywords=["tax mismatch", "due date"],
        unsafe_approval_keywords=["tax", "threshold"],
        expected_checks=["tax_code", "due_date", "approval_threshold"],
    ),
    "hard_fraud_detection": TaskFixture(
        task_id="hard_fraud_detection",
        difficulty="hard",
        description="Invoice splitting fraud detection.",
        invoices=[
            Invoice(
                invoice_id="INV-H-001",
                vendor_name="Acme Contractors",
                amount=9900.00,
                tax_code="VAT5",
                due_date="2026-04-21",
                po_number="PO-3001",
                currency="USD",
                line_items=["project phase A"],
                received_at="2026-04-02",
            ),
            Invoice(
                invoice_id="INV-H-002",
                vendor_name="Acme Contractors",
                amount=9950.00,
                tax_code="VAT5",
                due_date="2026-04-22",
                po_number="PO-3001",
                currency="USD",
                line_items=["project phase B"],
                received_at="2026-04-02",
            ),
            Invoice(
                invoice_id="INV-H-003",
                vendor_name="Acme Contractors",
                amount=1200.00,
                tax_code="VAT5",
                due_date="2026-04-17",
                po_number="PO-3002",
                currency="USD",
                line_items=["supplies"],
                received_at="2026-04-02",
            ),
        ],
        purchase_orders=[
            PurchaseOrder(po_number="PO-3001", vendor_name="Acme Contractors", approved_amount=20000.00, allowed_tax_codes=["VAT5"], approval_threshold=10000.0),
            PurchaseOrder(po_number="PO-3002", vendor_name="Acme Contractors", approved_amount=1200.00, allowed_tax_codes=["VAT5"], approval_threshold=10000.0),
        ],
        vendors=[VendorProfile(vendor_name="Acme Contractors", risk_level="high", known_aliases=["Acme Co"], historical_flags=["duplicate_invoices"])],
        policies=PolicyRules(max_due_days=30, duplicate_window_days=3, split_threshold_amount=10000),
        expected_outcome="escalate_case",
        perfect_actions=["review_invoice", "escalate_case"],
        worst_actions=["approve_invoice"],
        max_steps=10,
        clean_invoice_ids=["INV-H-003"],
        escalation_required_invoice_ids=["INV-H-001", "INV-H-002"],
        contradiction_pairs=[["approve_invoice", "escalate_case"]],
        success_keywords=["split", "duplicate", "fraud"],
        unsafe_approval_keywords=["split", "duplicate", "fraud"],
        expected_checks=["duplicate_window", "vendor_risk", "threshold_split"],
    ),
}


TASK_ORDER: list[str] = ["easy_single_mismatch", "medium_policy_tangle", "hard_fraud_detection"]
